# .github/workflows/codeql-scan.yml

name: "CodeQL Scan"

on:
  push:
    paths:
      - "samples/**"
  pull_request:
    paths:
      - "samples/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}ScanTest
  cancel-in-progress: true
  
permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        # Define the languages to scan.
        # Options: csharp, cpp, go, java, javascript, python, ruby
        language: ['javascript', 'python']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    # 1. Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    # 2. Autobuild (for compiled languages; skipped for Python/JS)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    # 3. Perform CodeQL Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Run OSV-Scanner
      uses: google/osv-scanner-action@latest
      id: scan
      with:
        scan-args: "--format sarif --output osv-results.sarif"
        
    - name: Upload SARIF file to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: osv-results.sarif
